= Reports

This repository contains some tools to generate reports.

== Installation

To install, first clone this repository on your machine:
```
git clone git@github.com:boar-network/reports.git
```

Make sure you have installed Go (at least 1.13). If so, run the build command:
```
go build
```

A binary named `reports` should be created.

== Configuration

To generate a report, you should provide a TOML file with basic
configuration properties. An example of such config is defined in
`./configs/config.toml.SAMPLE`.

Worth noting, the config TOML contains the `CustomersFile`
property which should point to a file containing the JSON with customer's
input data. You can find an example of this file in
`./configs/customers.json.SAMPLE`

== Usage

To generate reports, the `wkhtmltopdf` tool should be installed and available
from the command line. See https://wkhtmltopdf.org/downloads.html[their download page]
for details.

You can generate billing reports by doing:
```
./reports billings
```
Run this command with `-h` flag to see available options.
